
import com.sun.source.tree.TryTree;
import java.awt.Checkbox;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.*;
import java.sql.SQLException;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author mariogarsia
 */
public class Interfaz extends javax.swing.JFrame {
    
   //Variables palabra secreta y turno    
   String palabraSecreta;  
   int turno;
   Integer pGan = 0;
   String tema = null;
   
    
    
    /*
        
    
    
    
   
    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        
        
        /*CheckBoxTemas cbt = new CheckBoxTemas();
        cbt.setVisible(true);
        this.tema = cbt.tema;*/
        
        
       tema = JOptionPane.showInputDialog(this, "Que tema quieres?");
       
        
       try {
           //inicializamos las variables          
           this.palabraSecreta = cargarPalabra.selecionPalabraBD(tema);
       } catch (SQLException ex) {
           Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
       }
        turno = 1;
        pGan = 0;
        
        
        
        //SI NECESITAMOS SABER LA PALABRA, DESCOMENTAR LA LÍNEA DE ABAJO
        
        System.out.println("Trampas. Linea 70: " + palabraSecreta); 
        
        initComponents();
        
    }
    
   //método para resetear las filas de la pantalla
    private void resetearFila (ArrayList<javax.swing.JTextField> n_fila, String reset){
        Color def = new java.awt.Color(0, 0, 0, 10);
        for (int i = 0; i < n_fila.size(); i++){
            n_fila.get(i).setText(reset);
            n_fila.get(i).setBackground(def);
        }
    }
    
    
    //metodo para devolver el codigo de clores
    private void devolverColores (javax.swing.JTextField n_fila, char usuario, char secreta, String secret){
        if (usuario == secreta){
            n_fila.setBackground((new java.awt.Color(51, 204, 0)));
            n_fila.setText(Character.toString(usuario));
        } else if (secret.contains(String.valueOf(usuario))){
            n_fila.setBackground((new java.awt.Color(255, 233, 59)));
            n_fila.setText(Character.toString(usuario));
        } else{
            n_fila.setBackground((new java.awt.Color(0, 0, 0, 10)));
            n_fila.setText(Character.toString(usuario));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BarraUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        fila1_1 = new javax.swing.JTextField();
        fila1_2 = new javax.swing.JTextField();
        fila1_3 = new javax.swing.JTextField();
        fila1_4 = new javax.swing.JTextField();
        fila1_5 = new javax.swing.JTextField();
        fila2_1 = new javax.swing.JTextField();
        fila2_2 = new javax.swing.JTextField();
        fila2_3 = new javax.swing.JTextField();
        fila2_4 = new javax.swing.JTextField();
        fila2_5 = new javax.swing.JTextField();
        fila3_1 = new javax.swing.JTextField();
        fila3_2 = new javax.swing.JTextField();
        fila3_3 = new javax.swing.JTextField();
        fila3_4 = new javax.swing.JTextField();
        fila3_5 = new javax.swing.JTextField();
        fila4_1 = new javax.swing.JTextField();
        fila4_2 = new javax.swing.JTextField();
        fila4_3 = new javax.swing.JTextField();
        fila4_4 = new javax.swing.JTextField();
        fila4_5 = new javax.swing.JTextField();
        fila5_1 = new javax.swing.JTextField();
        fila5_2 = new javax.swing.JTextField();
        fila5_3 = new javax.swing.JTextField();
        fila5_4 = new javax.swing.JTextField();
        fila5_5 = new javax.swing.JTextField();
        fila6_1 = new javax.swing.JTextField();
        fila6_2 = new javax.swing.JTextField();
        fila6_3 = new javax.swing.JTextField();
        fila6_4 = new javax.swing.JTextField();
        fila6_5 = new javax.swing.JTextField();
        marcadorPartidas = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bienvenido a Wordle");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setText("Introduce una palabra:");

        jButton1.setText("OK");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        fila1_1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fila1_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fila1_1ActionPerformed(evt);
            }
        });

        fila1_2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fila1_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fila1_2ActionPerformed(evt);
            }
        });

        fila1_3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fila1_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fila1_3ActionPerformed(evt);
            }
        });

        fila1_4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fila1_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fila1_4ActionPerformed(evt);
            }
        });

        fila1_5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fila1_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fila1_5ActionPerformed(evt);
            }
        });

        fila2_1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fila2_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fila2_1ActionPerformed(evt);
            }
        });

        fila2_2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fila2_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fila2_2ActionPerformed(evt);
            }
        });

        fila2_3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fila2_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fila2_3ActionPerformed(evt);
            }
        });

        fila2_4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fila2_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fila2_4ActionPerformed(evt);
            }
        });

        fila2_5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fila2_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fila2_5ActionPerformed(evt);
            }
        });

        fila3_1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fila3_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fila3_1ActionPerformed(evt);
            }
        });

        fila3_2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fila3_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fila3_2ActionPerformed(evt);
            }
        });

        fila3_3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fila3_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fila3_3ActionPerformed(evt);
            }
        });

        fila3_4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fila3_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fila3_4ActionPerformed(evt);
            }
        });

        fila3_5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fila3_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fila3_5ActionPerformed(evt);
            }
        });

        fila4_1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fila4_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fila4_1ActionPerformed(evt);
            }
        });

        fila4_2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fila4_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fila4_2ActionPerformed(evt);
            }
        });

        fila4_3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fila4_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fila4_3ActionPerformed(evt);
            }
        });

        fila4_4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fila4_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fila4_4ActionPerformed(evt);
            }
        });

        fila4_5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fila4_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fila4_5ActionPerformed(evt);
            }
        });

        fila5_1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fila5_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fila5_1ActionPerformed(evt);
            }
        });

        fila5_2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fila5_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fila5_2ActionPerformed(evt);
            }
        });

        fila5_3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fila5_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fila5_3ActionPerformed(evt);
            }
        });

        fila5_4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fila5_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fila5_4ActionPerformed(evt);
            }
        });

        fila5_5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fila5_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fila5_5ActionPerformed(evt);
            }
        });

        fila6_1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fila6_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fila6_1ActionPerformed(evt);
            }
        });

        fila6_2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fila6_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fila6_2ActionPerformed(evt);
            }
        });

        fila6_3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fila6_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fila6_3ActionPerformed(evt);
            }
        });

        fila6_4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fila6_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fila6_4ActionPerformed(evt);
            }
        });

        fila6_5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fila6_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fila6_5ActionPerformed(evt);
            }
        });

        marcadorPartidas.setEditable(false);
        marcadorPartidas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        marcadorPartidas.setText("0");
        marcadorPartidas.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        marcadorPartidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marcadorPartidasActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        jLabel3.setText("Partidas ganadas:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fila1_1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fila1_2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fila1_3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fila1_4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fila1_5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fila2_1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fila2_2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fila2_3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fila2_4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fila2_5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fila3_1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fila3_2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fila3_3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fila3_4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fila3_5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fila4_1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fila4_2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fila4_3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fila4_4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fila4_5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fila5_1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fila5_2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fila5_3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fila5_4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fila5_5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fila6_1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fila6_2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fila6_3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fila6_4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fila6_5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(marcadorPartidas, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BarraUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(marcadorPartidas, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BarraUsuario))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fila1_1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fila1_2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fila1_3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fila1_4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fila1_5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fila2_1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fila2_3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fila2_4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fila2_2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fila2_5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fila3_1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fila3_2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fila3_3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fila3_4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fila3_5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fila4_1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fila4_2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fila4_3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fila4_4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fila4_5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fila5_1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fila5_2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fila5_3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fila5_4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fila5_5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fila6_1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fila6_2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fila6_3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fila6_4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fila6_5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        
       
        
        String palabraIntrod = BarraUsuario.getText().toUpperCase();
        String secretaMay = palabraSecreta.toUpperCase();
        
        
        ArrayList <javax.swing.JTextField> fila1 = new ArrayList<>();
        fila1.add(fila1_1);
        fila1.add(fila1_2);
        fila1.add(fila1_3);
        fila1.add(fila1_4);
        fila1.add(fila1_5);
        
        ArrayList <javax.swing.JTextField> fila2 = new ArrayList<>();
        fila2.add(fila2_1);
        fila2.add(fila2_2);
        fila2.add(fila2_3);
        fila2.add(fila2_4);
        fila2.add(fila2_5);
        
        ArrayList <javax.swing.JTextField> fila3 = new ArrayList<>();
        fila3.add(fila3_1);
        fila3.add(fila3_2);
        fila3.add(fila3_3);
        fila3.add(fila3_4);
        fila3.add(fila3_5);
        
        ArrayList <javax.swing.JTextField> fila4 = new ArrayList<>();
        fila4.add(fila4_1);
        fila4.add(fila4_2);
        fila4.add(fila4_3);
        fila4.add(fila4_4);
        fila4.add(fila4_5);
        
        ArrayList <javax.swing.JTextField> fila5 = new ArrayList<>();
        fila5.add(fila5_1);
        fila5.add(fila5_2);
        fila5.add(fila5_3);
        fila5.add(fila5_4);
        fila5.add(fila5_5);
        
        ArrayList <javax.swing.JTextField> fila6 = new ArrayList<>();
        fila6.add(fila6_1);
        fila6.add(fila6_2);
        fila6.add(fila6_3);
        fila6.add(fila6_4);
        fila6.add(fila6_5);
        
        
        
        //Inicio bloque if que comprueba si la palabra tiene la longitud correcta
        if (palabraIntrod.length() == 5){
         
            //Si el usuario NO acierta la palabra entra en el bloque if, con los switches 
            if(!palabraIntrod.equals(secretaMay)){
            switch (turno) {
                case 1:
                  for (int i = 0; i < palabraSecreta.length(); i++){
                char u = palabraIntrod.charAt(i);
                char s = secretaMay.charAt(i);
                
                devolverColores(fila1.get(i), u, s, secretaMay);
            }
                
             turno ++; 
             break;
             
                case 2:
                  for (int i = 0; i < palabraSecreta.length(); i++){
                char u = palabraIntrod.charAt(i);
                char s = secretaMay.charAt(i);
                  
                devolverColores(fila2.get(i), u, s, secretaMay);
                }
                  turno ++;
                  break;
                  
                  
                case 3:
                     for (int i = 0; i < palabraSecreta.length(); i++){
                char u = palabraIntrod.charAt(i);
                char s = secretaMay.charAt(i);
                
                devolverColores(fila3.get(i), u, s, secretaMay);
                }
                  turno ++;
                    break;
                    
                    case 4:
                     for (int i = 0; i < palabraSecreta.length(); i++){
                char u = palabraIntrod.charAt(i);
                char s = secretaMay.charAt(i);
                
                devolverColores(fila4.get(i), u, s, secretaMay);
                }
                  turno ++;
                    break;
                    
                    case 5:
                     
                     for (int i = 0; i < palabraSecreta.length(); i++){
                char u = palabraIntrod.charAt(i);
                char s = secretaMay.charAt(i);
                
                devolverColores(fila5.get(i), u, s, secretaMay);
                }
                 JOptionPane.showMessageDialog(this, "Último intento!"); //Muestra un mensaje de advertencia de que solo queda 1 intento
                  turno ++;
                    break;
                    
                    case 6:
                     
                     for (int i = 0; i < palabraSecreta.length(); i++){
                char u = palabraIntrod.charAt(i);
                char s = secretaMay.charAt(i);
                
                devolverColores(fila6.get(i), u, s, secretaMay);
                
                }
                     if (!palabraIntrod.equals(secretaMay)){
                    JOptionPane.showMessageDialog(this, "Te has quedado sin intentos! :( \n"
                                + "La palabra secreta era: " + secretaMay);
                    
                    
                    //Reseteamos la partida
                    resetearFila(fila1, "");
                    resetearFila(fila2, "");
                    resetearFila(fila3, "");
                    resetearFila(fila4, "");
                    resetearFila(fila5, "");
                    resetearFila(fila6, "");
                    
                         //reseteamos el turno y elegimos otra palabra secreta al azahar
                  turno = 1;
                 try {
                palabraSecreta = cargarPalabra.selecionPalabraBD(tema);
                   // System.out.println("Trampas. Linea 678 " + palabraSecreta);
            } catch (SQLException ex) {
                 Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
            }
                }
                     
                
                    break;
                    
                
                        
                default:
                    throw new AssertionError();
            }
            
            //fin del bloque siwtch
            
        } else { //fin del bloque if que comprueba que la palabra NO coincide
                JOptionPane.showMessageDialog(this, "Has adivinado la palabra secreta! \n " //Si la palabra SI coincide muestra este mensaje
                        + "Era: " + secretaMay);
                                               
                
                //sumamos al marcador un punto si el jugador acierta la palabra
                pGan++;
                String partidasGanadas = pGan.toString(); //convierte el pGan a String para usarlo como parámetro en el marcador
                marcadorPartidas.setText(partidasGanadas);
                
                
                
                 //Reseteamos la partida
                    resetearFila(fila1, "");
                    resetearFila(fila2, "");
                    resetearFila(fila3, "");
                    resetearFila(fila4, "");
                    resetearFila(fila5, "");
                    resetearFila(fila6, "");
                    
                    
                    
                         //reseteamos el turno y elegimos otra palabra secreta al azahar
                  turno = 1;
                 try {
                palabraSecreta = cargarPalabra.selecionPalabraBD(tema);
                // System.out.println("Trampas. Linea 721 " + palabraSecreta);
            } catch (SQLException ex) {
                 Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
            }  
                
            }
            
            BarraUsuario.setText(""); //reinicia el texto cuando la longitud de la palabra es correcta
             
            //fin del bloque if que comprueba que la palabra tenga la longitud correcta
            
        } else { //si la palabra no tiene la longitud correcta entre en este else
            JOptionPane.showMessageDialog(this, "La palabra debe ser de 5 letras.");
        }
        
       
     
        //fin del bloque action performed (clickar el botón)
    }//GEN-LAST:event_jButton1ActionPerformed

    private void fila1_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fila1_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fila1_1ActionPerformed

    private void fila1_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fila1_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fila1_2ActionPerformed

    private void fila1_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fila1_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fila1_3ActionPerformed

    private void fila1_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fila1_4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fila1_4ActionPerformed

    private void fila1_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fila1_5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fila1_5ActionPerformed

    private void fila2_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fila2_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fila2_1ActionPerformed

    private void fila2_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fila2_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fila2_2ActionPerformed

    private void fila2_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fila2_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fila2_3ActionPerformed

    private void fila2_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fila2_4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fila2_4ActionPerformed

    private void fila2_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fila2_5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fila2_5ActionPerformed

    private void fila3_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fila3_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fila3_1ActionPerformed

    private void fila3_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fila3_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fila3_2ActionPerformed

    private void fila3_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fila3_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fila3_3ActionPerformed

    private void fila3_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fila3_4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fila3_4ActionPerformed

    private void fila3_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fila3_5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fila3_5ActionPerformed

    private void fila4_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fila4_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fila4_1ActionPerformed

    private void fila4_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fila4_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fila4_2ActionPerformed

    private void fila4_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fila4_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fila4_3ActionPerformed

    private void fila4_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fila4_4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fila4_4ActionPerformed

    private void fila4_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fila4_5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fila4_5ActionPerformed

    private void fila5_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fila5_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fila5_1ActionPerformed

    private void fila5_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fila5_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fila5_2ActionPerformed

    private void fila5_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fila5_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fila5_3ActionPerformed

    private void fila5_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fila5_4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fila5_4ActionPerformed

    private void fila5_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fila5_5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fila5_5ActionPerformed

    private void fila6_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fila6_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fila6_1ActionPerformed

    private void fila6_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fila6_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fila6_2ActionPerformed

    private void fila6_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fila6_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fila6_3ActionPerformed

    private void fila6_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fila6_4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fila6_4ActionPerformed

    private void fila6_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fila6_5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fila6_5ActionPerformed

    private void marcadorPartidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marcadorPartidasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_marcadorPartidasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
            
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BarraUsuario;
    private javax.swing.JTextField fila1_1;
    private javax.swing.JTextField fila1_2;
    private javax.swing.JTextField fila1_3;
    private javax.swing.JTextField fila1_4;
    private javax.swing.JTextField fila1_5;
    private javax.swing.JTextField fila2_1;
    private javax.swing.JTextField fila2_2;
    private javax.swing.JTextField fila2_3;
    private javax.swing.JTextField fila2_4;
    private javax.swing.JTextField fila2_5;
    private javax.swing.JTextField fila3_1;
    private javax.swing.JTextField fila3_2;
    private javax.swing.JTextField fila3_3;
    private javax.swing.JTextField fila3_4;
    private javax.swing.JTextField fila3_5;
    private javax.swing.JTextField fila4_1;
    private javax.swing.JTextField fila4_2;
    private javax.swing.JTextField fila4_3;
    private javax.swing.JTextField fila4_4;
    private javax.swing.JTextField fila4_5;
    private javax.swing.JTextField fila5_1;
    private javax.swing.JTextField fila5_2;
    private javax.swing.JTextField fila5_3;
    private javax.swing.JTextField fila5_4;
    private javax.swing.JTextField fila5_5;
    private javax.swing.JTextField fila6_1;
    private javax.swing.JTextField fila6_2;
    private javax.swing.JTextField fila6_3;
    private javax.swing.JTextField fila6_4;
    private javax.swing.JTextField fila6_5;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField marcadorPartidas;
    // End of variables declaration//GEN-END:variables
}
